using System;
using System.Collections.Generic;
using System.Text;

namespace DSA.Oops
{
    public class ServiceUIPlaceholders
    {
        public const string UniqueSessionIDPlaceholder = "$SESSIONID$";
        public const string SubmitPlaceholder = "#submit#";
        public const string FormActionPlaceholder = "$FORMACTION$";
        public const string HttpMethodPlaceholder = "$HTTPMETHOD$";
        public const string PackDescriptionPlaceholder = "$PACKDESCRIPTION$";
        public const string PackValidityPlaceholder = "$PACKVALIDITY$";
        public const string PackAmountPlaceholder = "$PACKAMOUNT$";
        public const string PackIDPlaceholder = "$PACKID$";
        public const string PackTypePlaceholder = "$PACKTYPE$";
        public const string PackTypeDisplayNamePlaceholder = "$PACKTYPEDISPLAYNAME$";
        public const string PackDiscountedPlaceholder = "$PACKDISCOUNTED$";
        public const string PackCoinsQuantityPlaceholder = "$PACKCOINSQUANTITY$";
        public const string PackCoinsPeriodPlaceholder = "$PACKCOINSPERIOD$";
        public const string PackCoinsPeriodUnitPlaceholder = "$PACKCOINSPERIODUNIT$";
        public const string RedirectURLPlaceholder = "$REDIRECTURL$";
        public const string RetryURLPlaceholder = "$RETRYREDIRECTURL$";
        public const string AmountChargedPlaceholder = "$AMOUNTCHARGED$";
        public const string AntiForgeryTokenPlaceholder = "$AFT$";
        public const string ResendOTPPlaceholder = "$RESENDOTP$";
        public const string CancelURLPlaceholder = "$CANCELURL$";
        public const string GenericMessageTextPlaceholder = "$GENERICMESSAGETEXT$";
        public const string SubmitWhenClickedAttrName = "submitwhenclicked";
        public const string BannerImageSRCPlaceholder = "$BANNERIMAGESRC$";
        public const string LogoImageSRCPlaceholder = "$LOGOIMAGESRC$";
        public const string GTMDataLayer = "$DATALAYER$";
        public const string BodyInLayoutPlaceholder = "$BODY$";
        public const string PageTitle = "$PAGETITLE$";
        public const string MSISDNPlaceholder = "$MSISDN$";
        public const string UMRIDPlaceholder = "$UMRID$";
        public const string CSSTemplatePlaceholder = "$STYLETEMPLATE$";
        public const string ServiceNamePlaceholder = "$SERVICENAME$";
        public const string UITemplateProjectNamePlaceholder = "$UITEMPLATENAME$";
        public const string ContentTitlePlaceholder = "$BANNEROVERLAYTEXT$";
        public const string UserSubscriptionStatusPlaceholder = "$SUBSCRIPTIONSTATUS$";
        public const string VoucherCodePlaceholder = "$VOUCHERCODE$";
        public const string VoucherRedemptionURLPlaceholder = "$VOUCHERREDEMPTIONURL$";
        public const string ExternalFraudDetectionScriptPlaceholder = "$FRAUDDETECTIONJAVASCRIPT$";
        public const string GTMTrackingIDPlaceholder = "$COMMON_GTM_TAG_ID$";
        public const string OperatorGTMTrackingIDPlaceholder = "$OPERATOR_GTM_TAG_ID$";
        public const string BannerUrlList = "$BANNERLIST$";
        public const string PLANPRICE = "$PLANPRICE$";
        public const string PROFILECOUNT = "$PROFILECOUNT$";
        public const string SCREENALLOWEDCOUNT = "$SCREENALLOWEDCOUNT$";
        public const string NEXTRENEWALDATE = "$NEXTRENEWALDATE$";
        public const string DeactivationInitiatedDate = "$DEACTIVATIONINITIATEDDATE$";
        public const string ErrorCode = "$ERRORCODE$";
        public const string DisabledButtonClass = "$DISABLEDSUBSCRIPTIONCAPPING$";
        public const string ContentPrimaryImageUrl = "$CONTENTPRIMARYIMAGEURL$";
        public const string ContentPrviewUrl = "$CONTENTPREVIEWURL$";
        public const string ContentTrackName = "$CONTENTTRACKNAME$";
        public const string ContentArtistName = "$CONTENTARTISTNAME$";
        public const string ContentDescription = "$CONTENTDESCRIPTION$";
        public const string ContentShortDescription = "$CONTENTSHORTDESCRIPTION$";
        public const string ContentPostBuyDescription = "$CONTENTPOSTBUYDESCRIPTION$";
        public const string ContentPostBuyShortDescription = "$CONTENTPOSTBUYSHORTDESCRIPTION$";
        public const string ForgotPasswordPlaceholder = "$FORGOTPASSWORD$";
        public const string AuthenticationErrorMessage = "$AUTHENTICATIONERRORMESSAGE$";
        public const string ActPendingStatus = "$ACTPENDINGSTATUS$";
        public const string ConsentPendingStatus = "$CONSENTPENDINGSTATUS$";
        public const string BillingOptionDisplayNamePlaceholder = "$BILLINGOPTIONDISPLAYNAME$";
        public const string BillingOptionDescriptionPlaceholder = "$BILLINGOPTIONDESCRIPTION$";
        public const string BillingOptionLogoImageUrlPlaceholder = "$BILLINGOPTIONLOGOIMAGEURL$";
        public const string BillingOptionLogoForwardImageUrlPlaceholder = "$BILLINGOPTIONLOGOFORWARDIMAGEURL$";
        public const string BillingOptionSequenceNumberPlaceholder = "$BILLINGOPTIONSEQUENCENUMBER$";
        public const string RetryRedirectURLPlaceholder = "$RETRYREDIRECTURL$";
        public const string QualityCheckScriptPlaceholder = "$QUALITYCHECKJAVASCRIPT$";
        public const string GoogleRechaptchaV2SiteKey = "$GOOGLERECAPTCHAV2SITEKEY$";
        public const string AgeVerificationEnabledPlaceholder = "$AGEVERIFICATIONENABLED$";
        public const string ClientActivityLoggingUrlPlaceholder = "$CLIENTACTIVITYLOGGINGURL$";
        public const string WifiServiceJSFileUrl = "$WIFISERVICEJSFILEURL$";
        public const string WifiServiceApiKey = "$WIFISERVICEAPIKEY$";
        public const string WifiServiceStoreCookiePath = "$WIFISERVICESTORECOOKIEPATH$";
        public const string WifiServiceStoreCookieUseSSL = "$WIFISERVICESTORECOOKIEUSESSL$";
        public const string WifiServiceUseSSL = "$WIFISERVICEUSESSL$";
        public const string WifiServiceIsStoreCookieSetKey = "$WIFISERVICEISSTORECOOKIESETKEY$";
        public const string WifiServiceStoreCookieSetWaitTime = "$WIFISERVICESTORECOOKIESETWAITTIME$";
        public const string IsUserIdentified = "$ISUSERIDENTIFIED$";
        public const string SendOtpActionInfoScope = "$SENDOTPACTIONINFOSCOPE$";
        public const string RequestedActionPlaceholder = "$REQUESTEDACTION$";
        public const string LocaleCodeholder = "$LOCALECODE$";
        public const string PreFilledUserOTPValue = "$PREFILLEDUSEROTPVALUE$";
    }
}
